#spring:
#  security:
#    user:
#      name: user
#      password: 12345

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true

security:
  token:
    secret: 2472B08201704D96A5844807E43BA02A9E0CCA945381123A82B1DD4E852B9325
    timeout: 30000

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG