
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

hash:
  sha256:
    salt: 70DD29E1BE48BBA013A2E7EDF6F10861F82DD9C9C0C2A1419C69D3CD74513452
  sha512:
    salt: 98ACB4E82C38C5C2D5166EB05023CAB5455035FA4659B402FB1389C2D66455A6
  pbkdf2:
    salt: B6FC08FA50377E5E646CAE93C6B12E74F01D6D4E4DAE1F54DA53EB4D340EC75C
    iterations: 185000
    hashWidth: 256
  bcrypt:
    strength: 12