
server:
  port: 8087

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
