
server:
  port: 8082

basic:
  auth:
    tokens:
      -
        token: bWluaGR1Y0BnbWFpbC5jb206MTIzNDU2
        roles:
          - ADMIN
      - token: bWluaGR1YzFAZ21haWwuY29tOjEyMzQ1Ng==
        roles:
          - USER